<a href="https://colab.research.google.com/github/9bishal/content-based-movie-recommender/blob/main/content_based_movie_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [460]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [461]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [462]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [463]:
movies.shape

(4803, 20)

In [464]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [465]:
movies = movies.merge(credits,on='title')

In [466]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [467]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [468]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [469]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [470]:
import ast

In [471]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name'])
    return L

In [472]:
movies.dropna(inplace=True)

In [473]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [474]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [475]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [476]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [477]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [478]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [479]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [480]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [481]:
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
2077,8456,Never Back Down,Rebellious Jake Tyler is lured into an ultimat...,"[Drama, Action]","[rebel, martial arts, underground, fight, trai...","[Sean Faris, Amber Heard, Cam Gigandet]",[Jeff Wadlow]
2374,27380,Megaforce,Megaforce is an elite multi-national military ...,"[Adventure, Action, Science Fiction]","[dictator, soldier, electronic music score, mi...","[Barry Bostwick, Michael Beck, Persis Khambatta]",[Hal Needham]
1772,303858,Money Monster,Financial TV host Lee Gates and his producer P...,[Thriller],"[bomb, sniper, tv show, hostage drama, police,...","[George Clooney, Julia Roberts, Jack O'Connell]",[Jodie Foster]
2360,2575,The Tailor of Panama,A British spy is banished to Panama after havi...,"[Drama, Thriller]","[dancing, spy, birthday, map, fireworks, bridg...","[Pierce Brosnan, Geoffrey Rush, Jamie Lee Curtis]",[John Boorman]
3724,510,One Flew Over the Cuckoo's Nest,While serving time for insanity at a state men...,[Drama],"[individual, rebel, self-destruction, wheelcha...","[Jack Nicholson, Louise Fletcher, Danny DeVito]",[Miloš Forman]

In [482]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [483]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [484]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [485]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [486]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [487]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])
new.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [488]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [489]:
new_df = movies[['movie_id', 'title', 'tags']]

In [490]:
new_df['tags']=new_df['tags'].apply(lambda x: " ". join(x))

<ipython-input-490-3aff66d12fc3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x: " ". join(x))

In [491]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [492]:
new_df['tags']=new_df['tags'].apply( lambda x: x.lower())

<ipython-input-492-7d4629469e6a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply( lambda x: x.lower())

In [493]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [494]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

##Breaking down the Algorithm

In [495]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

Yes! You got it almost right! Let me refine it a bit for **perfect understanding**. 🚀  

---

## **How `CountVectorizer(max_features=5000, stop_words='english')` Works**
1. **Removes stop words** (like "in", "the", "is", "I", etc.).
2. **Builds a vocabulary** of at most **5000 unique words** (excluding stop words).
3. **Converts text into a numerical representation** (Bag-of-Words model), where:
   - Each row represents a document.
   - Each column represents a word from the vocabulary.
   - The values represent **word frequency** in that document.

---

### **Step-by-Step Example**
#### **Input Texts**
```python
documents = [
    "I love Python and Python loves me!",
    "Python is great for data science.",
    "Machine learning is amazing and useful."
]
```

#### **Step 1: Tokenization (Breaking Text into Words)**
```
["I", "love", "Python", "and", "Python", "loves", "me"]
["Python", "is", "great", "for", "data", "science"]
["Machine", "learning", "is", "amazing", "and", "useful"]
```

---

#### **Step 2: Removing Stop Words (`stop_words='english'`)**
Stop words like **"I", "is", "and", "for"** are removed:
```
["love", "Python", "Python", "loves", "me"]
["Python", "great", "data", "science"]
["Machine", "learning", "amazing", "useful"]
```

---

#### **Step 3: Building a Vocabulary (with `max_features=5000`)**
- Unique words in the dataset (after removing stop words):
  ```
  ['amazing', 'data', 'great', 'learning', 'love', 'loves', 'machine', 'me', 'python', 'science', 'useful']
  ```
- Each word is given an index:
  ```
  amazing → 0
  data → 1
  great → 2
  learning → 3
  love → 4
  loves → 5
  machine → 6
  me → 7
  python → 8
  science → 9
  useful → 10
  ```

---

#### **Step 4: Creating the Bag-of-Words Matrix**
Each document is converted into a numerical **word frequency matrix**:

|  | amazing | data | great | learning | love | loves | machine | me | python | science | useful |
|---|---------|------|-------|----------|------|-------|---------|----|--------|---------|--------|
| **Doc 1** | 0 | 0 | 0 | 0 | 1 | 1 | 0 | 1 | 2 | 0 | 0 |
| **Doc 2** | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 1 | 1 | 0 |
| **Doc 3** | 1 | 0 | 0 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | 1 |

---

#### **Step 5: Converting to Array**
```python
cv = CountVectorizer(max_features=5000, stop_words='english')
X = cv.fit_transform(documents).toarray()
print(X)
```
Output:
```
[[0 0 0 0 1 1 0 1 2 0 0]
 [0 1 1 0 0 0 0 0 1 1 0]
 [1 0 0 1 0 0 1 0 0 0 1]]
```

---

### **🚀 Final Understanding**
✔ **Stop words removed first.**  
✔ **Vocabulary (max 5000 words) is built.**  
✔ **Each document is converted into a word frequency vector.**  

💡 Now, do you want to test it with your own sentences? 😃

In [496]:
cv.fit_transform(new_df['tags']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [497]:
cv.fit_transform(new_df['tags']).toarray().shape

(4806, 5000)

It mean the 4806 movie, and 5000 as the words

In [498]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [499]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [500]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [501]:
words=cv.get_feature_names_out()

In [502]:
words

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [503]:
import nltk

In [504]:
%pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from nltk) (4.67.1)

##Working with the NPL library

The above data 'word' include some of the unnecessary data like 'dancing' and 'dance'. In order to remove this one we use NPL Library called as `nltk`
So, Basically it works with the `root words`

In [505]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer

In [506]:
def stem(text):
  y=[]
  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y) #back convert to string

In [507]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()  # Initialize the stemmer

print(ps.stem("loving"))  # Correct way to use stem()

love

Example of the movie data

In [508]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

Applying to the data 'tags'

In [509]:
new_df['tags']=new_df['tags'].apply(stem)

<ipython-input-509-402dd7cb6b10>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [510]:
from sklearn.metrics.pairwise import cosine_similarity

### **1️⃣ What is Cosine Similarity?**  
Cosine similarity measures how similar two vectors are, **based on their direction rather than their magnitude**.  

It calculates the **cosine of the angle** between two vectors.  

#### **Formula:**
\[
\text{cosine similarity} = \frac{A \cdot B}{||A|| \times ||B||}
\]
where:  
- \( A \cdot B \) is the **dot product** of the two vectors.  
- \( ||A|| \) and \( ||B|| \) are the **magnitudes (norms)** of the vectors.  

#### **Range of values:**
- `1` → **Completely similar** (same direction)  
- `0` → **No similarity** (orthogonal vectors)  
- `-1` → **Completely opposite** (opposite direction)  

---

### **2️⃣ How Does `cosine_similarity(vectors)` Work?**  
- It takes an **array of vectors** (e.g., text embeddings, word frequency counts).  
- Computes the **cosine similarity** between each pair of vectors.  
- Returns a **similarity matrix**.

In [511]:
cosine_similarity(vectors)

array([[1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
        0.        ],
       [0.08964215, 1.        , 0.06350006, ..., 0.02635231, 0.        ,
        0.        ],
       [0.06071767, 0.06350006, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.02519763, 0.02635231, 0.02677398, ..., 1.        , 0.07352146,
        0.04774099],
       [0.0277885 , 0.        , 0.        , ..., 0.07352146, 1.        ,
        0.05264981],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05264981,
        1.        ]])

In [512]:
cosine_similarity(vectors).shape

(4806, 4806)

In [513]:
similarity=cosine_similarity(vectors)

In [514]:
similarity

array([[1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
        0.        ],
       [0.08964215, 1.        , 0.06350006, ..., 0.02635231, 0.        ,
        0.        ],
       [0.06071767, 0.06350006, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.02519763, 0.02635231, 0.02677398, ..., 1.        , 0.07352146,
        0.04774099],
       [0.0277885 , 0.        , 0.        , ..., 0.07352146, 1.        ,
        0.05264981],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05264981,
        1.        ]])

In [515]:
similarity[0]

array([1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
       0.        ])

This mean, the 1st movies have this much of similarrity to every movie

In [516]:
similarity[0].shape

(4806,)

In [517]:
similarity[0]

array([1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
       0.        ])

(0)th represents, the first movie is simililar to itsellf

In [518]:
similarity[1]

array([0.08964215, 1.        , 0.06350006, ..., 0.02635231, 0.        ,
       0.        ])


(1)st, the second movie is simililar to itsellf

We just neewd to find the 5 movies that are similar to the currently watching movie, using the `sorted()` function we could easily find it,

In [519]:
sorted(similarity[0], reverse=True)

[1.0,
 0.26089696604360174,
 0.2581988897471611,
 0.25110592822973776,
 0.24944382578492943,
 0.24846467329894412,
 0.24397501823713333,
 0.243599382882345,
 0.24147264420814754,
 0.23904572186687872,
 0.22677868380553634,
 0.2238868314198225,
 0.22230800575069137,
 0.22190115272469205,
 0.22131333406899523,
 0.2173253797873328,
 0.21653278478430665,
 0.2164218276749025,
 0.2162249910469341,
 0.2162249910469341,
 0.2138089935299395,
 0.2125118592516207,
 0.21251185925162067,
 0.21251185925162067,
 0.2114722130550724,
 0.21147221305507238,
 0.2059714602177749,
 0.20498001542269692,
 0.20283702113484398,
 0.2,
 0.1980534816610477,
 0.19518001458970666,
 0.19518001458970666,
 0.19518001458970663,
 0.19518001458970663,
 0.19477964490741226,
 0.19451950503185494,
 0.1938916835823703,
 0.1938916835823703,
 0.19320245583349133,
 0.19194297398747862,
 0.1916629694999819,
 0.18869127060994534,
 0.18832944617230335,
 0.18752289237539818,
 0.18752289237539815,
 0.18708286933869708,
 0.18442777839082936,
 0.1825741858350554,
 0.18257418583505536,
 0.18257418583505536,
 0.18182745801939793,
 0.18018749253911176,
 0.17928429140015903,
 0.1765469659009499,
 0.1763834207376394,
 0.17622684421256032,
 0.17445567519772937,
 0.1739313106957345,
 0.173137462139922,
 0.17251638983558856,
 0.17142857142857143,
 0.1690308509457033,
 0.1690308509457033,
 0.1690308509457033,
 0.16903085094570328,
 0.16903085094570328,
 0.16673100431301852,
 0.16574838603294897,
 0.16574838603294897,
 0.16408253082847338,
 0.16265001215808886,
 0.16239958858823,
 0.16239958858823,
 0.16035674514745463,
 0.16035674514745463,
 0.15971914124998493,
 0.15971914124998493,
 0.15694120514358612,
 0.1564921592871903,
 0.1553638665664663,
 0.1546617786679401,
 0.15430334996209188,
 0.15430334996209188,
 0.15430334996209188,
 0.15289415743128765,
 0.15289415743128765,
 0.15179418517972906,
 0.15179418517972906,
 0.15118578920369088,
 0.15118578920369088,
 0.15026857675938213,
 0.14953343588376802,
 0.14754222271266348,
 0.14754222271266348,
 0.14754222271266348,
 0.14638501094227999,
 0.1456438162508838,
 0.1449427589131121,
 0.1449427589131121,
 0.1449427589131121,
 0.1449427589131121,
 0.14414999403128942,
 0.14414999403128942,
 0.14414999403128942,
 0.14414999403128942,
 0.14285714285714285,
 0.14285714285714285,
 0.14201432049934523,
 0.14098147537004826,
 0.14098147537004826,
 0.14085904245475275,
 0.14085904245475275,
 0.1406421692815486,
 0.1406421692815486,
 0.1406421692815486,
 0.1406421692815486,
 0.1389425035941821,
 0.13801311186847084,
 0.13801311186847084,
 0.13801311186847084,
 0.13801311186847084,
 0.13801311186847082,
 0.13710212427677043,
 0.13710212427677043,
 0.13710212427677043,
 0.13662601021279464,
 0.13572417850765922,
 0.13533299049019168,
 0.13533299049019168,
 0.13522468075656266,
 0.13522468075656266,
 0.13522468075656266,
 0.1336306209562122,
 0.13316902848554255,
 0.13259870882635919,
 0.13259870882635919,
 0.13259870882635919,
 0.13259870882635919,
 0.13259870882635919,
 0.13259870882635919,
 0.13199091933711365,
 0.1309307341415954,
 0.13041013273932528,
 0.13041013273932528,
 0.13041013273932528,
 0.1301200097264711,
 0.1301200097264711,
 0.12888481555661674,
 0.12888481555661674,
 0.12880163722232754,
 0.12777531299998796,
 0.12777531299998796,
 0.12741179785940637,
 0.12741179785940637,
 0.1267731382092775,
 0.1267731382092775,
 0.12598815766974242,
 0.12598815766974242,
 0.12598815766974242,
 0.12555296411486888,
 0.12555296411486888,
 0.12555296411486888,
 0.12555296411486888,
 0.12555296411486888,
 0.12555296411486888,
 0.1246111965698067,
 0.12461119656980668,
 0.12344267996967351,
 0.12344267996967351,
 0.12344267996967351,
 0.12344267996967351,
 0.12327841818038447,
 0.12327841818038447,
 0.12327841818038446,
 0.12298800925361816,
 0.12298800925361816,
 0.12198750911856666,
 0.12073632210407378,
 0.12073632210407378,
 0.12073632210407378,
 0.12036162814275589,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343935,
 0.11952286093343935,
 0.11952286093343935,
 0.11952286093343935,
 0.11952286093343935,
 0.11952286093343935,
 0.1187013882373396,
 0.1183452670827877,
 0.11769797726729994,
 0.11769797726729994,
 0.11769797726729994,
 0.11769797726729994,
 0.11769797726729994,
 0.11720180773462385,
 0.11710800875382396,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11595420713048966,
 0.11595420713048966,
 0.11595420713048966,
 0.11501092655705902,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276816,
 0.1129384878631564,
 0.1129384878631564,
 0.1129384878631564,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.11194341570991125,
 0.11194341570991125,
 0.11194341570991125,
 0.11194341570991125,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11097419040461878,
 0.11065666703449763,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11002971203391539,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10826639239215334,
 0.10826639239215334,
 0.10821091383745127,
 0.10821091383745125,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10690449676496976,
 0.10690449676496976,
 0.10690449676496976,
 0.10690449676496976,
 0.10690449676496976,
 0.10690449676496976,
 0.10690449676496976,
 0.10631548679075009,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.10559273546969093,
 0.10559273546969093,
 0.10559273546969093,
 0.10559273546969093,
 0.10559273546969093,
 0.10559273546969093,
 0.10460520656316097,
 0.10432810619146021,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10079052613579392,
 0.10079052613579392,
 0.09968895725584535,
 0.09960238411119947,
 0.09960238411119947,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.09862273454430757,
 0.09862273454430757,
 0.09862273454430757,
 0.09862273454430757,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09694584179118515,
 0.09694584179118515,
 0.09658905768325902,
 0.09658905768325902,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09561828874675149,
 0.09561828874675149,
 0.09508728264112047,
 0.09467621366623016,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09390602830316849,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09333167411831966,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09200874124564722,
 0.09200874124564722,
 0.09200874124564722,
 0.09200874124564722,
 0.09200874124564722,
 0.09200874124564722,
 0.09116846116771035,
 0.09116846116771035,
 0.09116846116771035,
 0.09116846116771035,
 0.09116846116771035,
 0.09116846116771035,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09009374626955588,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.089554732567929,
 0.089554732567929,
 0.08877935232369503,
 0.08877935232369503,
 0.08877935232369503,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047495,
 0.0880237696271323,
 0.0880237696271323,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.086568731069961,
 0.086568731069961,
 0.08656873106996099,
 0.08586775814821836,
 0.08586775814821836,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.08518354199999197,
 0.08518354199999197,
 0.08518354199999197,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08386278693775347,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.08058229640253803,
 0.08024108542850393,
 0.08017837257372731,
 0.08017837257372731,
 0.08017837257372731,
 0.08017837257372731,
 0.07985957062499247,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.07913425882489307,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359515,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07655590023509526,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07606982611289638,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07476671794188403,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07466533929465573,
 0.07396705090823068,
 0.07396705090823068,
 0.07396705090823068,
 0.07396705090823068,
 0.07396705090823068,
 0.07396705090823068,
 0.07396705090823068,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07244179326244427,
 0.07244179326244427,
 0.07244179326244427,
 0.07244179326244427,
 0.07244179326244427,
 0.07244179326244427,
 0.07244179326244427,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07168504827326538,
 0.07126966450997983,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.0703210846407743,
 0.0703210846407743,
 0.0703210846407743,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423541,
 0.06900655593423541,
 0.06900655593423541,
 0.06900655593423541,
 0.06900655593423541,
 0.06900655593423541,
 0.06900655593423541,
 0.06837634587578277,
 0.06837634587578276,
 0.06837634587578276,
 0.06776309271789384,
 0.06776309271789384,
 0.06776309271789384,
 0.06776309271789384,
 0.06776309271789384,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06716604942594674,
 0.06658451424277127,
 0.06658451424277127,
 0.06658451424277127,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06601782722034923,
 0.06601782722034923,
 0.06601782722034923,
 0.06601782722034923,
 0.0654653670707977,
 0.0654653670707977,
 0.0654653670707977,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06492654830247076,
 0.06492654830247076,
 0.06446583712203043,
 0.06440081861116377,
 0.06440081861116377,
 0.06440081861116377,
 0.06440081861116377,
 0.06440081861116377,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06338656910463875,
 0.0628970902033151,
 0.0628970902033151,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06241877839323591,
 0.06198013080533033,
 0.06195121541733006,
 0.06195121541733006,

We need to keep even the indexes, we `enumerated()` function is used, and list is used to convert into list

It mean that the, the movie at the 0th index is "0.08964214570007951" distance from the 1st index movie

In [520]:
list(enumerate(similarity[0]))

[(0, 1.0),
 (1, 0.08964214570007951),
 (2, 0.060717674071891624),
 (3, 0.03984095364447979),
 (4, 0.18257418583505536),
 (5, 0.1183452670827877),
 (6, 0.023218173010628604),
 (7, 0.1763834207376394),
 (8, 0.06388765649999398),
 (9, 0.07733088933397005),
 (10, 0.11769797726729994),
 (11, 0.081199794294115),
 (12, 0.09583148474999097),
 (13, 0.04733810683311508),
 (14, 0.11428571428571427),
 (15, 0.05096471914376255),
 (16, 0.08226127456606226),
 (17, 0.15026857675938213),
 (18, 0.11194341570991125),
 (19, 0.08728715609439694),
 (20, 0.058167505074711086),
 (21, 0.09416472308615166),
 (22, 0.06900655593423542),
 (23, 0.09759000729485331),
 (24, 0.0563436169819011),
 (25, 0.03877833671647406),
 (26, 0.17142857142857143),
 (27, 0.18752289237539818),
 (28, 0.12555296411486888),
 (29, 0.07100716024967263),
 (30, 0.07319250547113999),
 (31, 0.15971914124998493),
 (32, 0.09116846116771035),
 (33, 0.1057361065275362),
 (34, 0.0),
 (35, 0.11065666703449761),
 (36, 0.19194297398747862),
 (37, 0.08451542547285165),
 (38, 0.0628970902033151),
 (39, 0.08827348295047496),
 (40, 0.0563436169819011),
 (41, 0.14638501094227999),
 (42, 0.0),
 (43, 0.09759000729485333),
 (44, 0.040996003084539386),
 (45, 0.09116846116771035),
 (46, 0.1765469659009499),
 (47, 0.2164218276749025),
 (48, 0.06776309271789384),
 (49, 0.06388765649999398),
 (50, 0.12344267996967351),
 (51, 0.08586775814821836),
 (52, 0.1449427589131121),
 (53, 0.04931136727215379),
 (54, 0.035245368842512066),
 (55, 0.07655590023509526),
 (56, 0.14414999403128942),
 (57, 0.028988551782622416),
 (58, 0.04733810683311508),
 (59, 0.08024108542850393),
 (60, 0.028988551782622416),
 (61, 0.2162249910469341),
 (62, 0.08199200616907877),
 (63, 0.09200874124564722),
 (64, 0.03138824102871722),
 (65, 0.020965696734438367),
 (66, 0.02492223931396134),
 (67, 0.17928429140015903),
 (68, 0.13259870882635919),
 (69, 0.0520265981714472),
 (70, 0.081199794294115),
 (71, 0.08226127456606226),
 (72, 0.12344267996967351),
 (73, 0.03779644730092272),
 (74, 0.22677868380553634),
 (75, 0.09258200997725513),
 (76, 0.07824607964359516),
 (77, 0.014824986333222025),
 (78, 0.05345224838248488),
 (79, 0.07824607964359516),
 (80, 0.03450327796711771),
 (81, 0.11710800875382396),
 (82, 0.08336550215650926),
 (83, 0.22190115272469205),
 (84, 0.1456438162508838),
 (85, 0.10631548679075009),
 (86, 0.08827348295047496),
 (87, 0.11595420713048966),
 (88, 0.09107651110783743),
 (89, 0.06146576398025575),
 (90, 0.06506000486323554),
 (91, 0.15971914124998493),
 (92, 0.07100716024967263),
 (93, 0.05039526306789696),
 (94, 0.16574838603294897),
 (95, 0.12461119656980668),
 (96, 0.08964214570007951),
 (97, 0.07476671794188401),
 (98, 0.08827348295047496),
 (99, 0.029880715233359837),
 (100, 0.07377111135633174),
 (101, 0.08827348295047496),
 (102, 0.11194341570991125),
 (103, 0.08877935232369503),
 (104, 0.05884898863364997),
 (105, 0.10811249552346706),
 (106, 0.0447773662839645),
 (107, 0.09200874124564722),
 (108, 0.16903085094570328),
 (109, 0.07968190728895957),
 (110, 0.024397501823713332),
 (111, 0.15430334996209188),
 (112, 0.09107651110783743),
 (113, 0.052796367734845466),
 (114, 0.052796367734845466),
 (115, 0.05413319619607667),
 (116, 0.057142857142857134),
 (117, 0.060717674071891624),
 (118, 0.017622684421256033),
 (119, 0.048795003647426664),
 (120, 0.0),
 (121, 0.09107651110783743),
 (122, 0.09583148474999097),
 (123, 0.12198750911856666),
 (124, 0.06837634587578277),
 (125, 0.07985957062499247),
 (126, 0.11595420713048966),
 (127, 0.13572417850765922),
 (128, 0.0),
 (129, 0.10559273546969093),
 (130, 0.03194382824999699),
 (131, 0.1126872339638022),
 (132, 0.045584230583855176),
 (133, 0.033149677206589796),
 (134, 0.13522468075656266),
 (135, 0.0),
 (136, 0.025482359571881275),
 (137, 0.034324965259398446),
 (138, 0.08226127456606226),
 (139, 0.10821091383745127),
 (140, 0.05096471914376255),
 (141, 0.11338934190276816),
 (142, 0.09759000729485331),
 (143, 0.06965451903188581),
 (144, 0.055577001437672836),
 (145, 0.02258769757263128),
 (146, 0.017251638983558856),
 (147, 0.06277648205743444),
 (148, 0.1057361065275362),
 (149, 0.173137462139922),
 (150, 0.18869127060994534),
 (151, 0.20498001542269692),
 (152, 0.06388765649999398),
 (153, 0.086568731069961),
 (154, 0.033149677206589796),
 (155, 0.0),
 (156, 0.06658451424277127),
 (157, 0.1057361065275362),
 (158, 0.15289415743128765),
 (159, 0.06761234037828133),
 (160, 0.09694584179118515),
 (161, 0.035245368842512066),
 (162, 0.03688555567816587),
 (163, 0.05413319619607667),
 (164, 0.09416472308615166),
 (165, 0.04984447862792268),
 (166, 0.11952286093343935),
 (167, 0.06900655593423542),
 (168, 0.16035674514745463),
 (169, 0.11952286093343936),
 (170, 0.09200874124564722),
 (171, 0.029424494316824985),
 (172, 0.15118578920369088),
 (173, 0.024397501823713332),
 (174, 0.11115400287534567),
 (175, 0.0515539262226467),
 (176, 0.030860669992418377),
 (177, 0.0),
 (178, 0.02577696311132335),
 (179, 0.07559289460184544),
 (180, 0.023904572186687872),
 (181, 0.02344036154692477),
 (182, 0.10690449676496976),
 (183, 0.07466533929465573),
 (184, 0.1825741858350554),
 (185, 0.055577001437672836),
 (186, 0.040697846377823976),
 (187, 0.14085904245475275),
 (188, 0.02258769757263128),
 (189, 0.08199200616907877),
 (190, 0.08386278693775347),
 (191, 0.0515539262226467),
 (192, 0.0),
 (193, 0.08728715609439694),
 (194, 0.0),
 (195, 0.06506000486323554),
 (196, 0.05884898863364997),
 (197, 0.048795003647426664),
 (198, 0.059761430466719674),
 (199, 0.11720180773462385),
 (200, 0.07755667343294811),
 (201, 0.0),
 (202, 0.03450327796711771),
 (203, 0.08827348295047496),
 (204, 0.02672612419124244),
 (205, 0.08199200616907877),
 (206, 0.09694584179118515),
 (207, 0.0857142857142857),
 (208, 0.1690308509457033),
 (209, 0.03877833671647406),
 (210, 0.05484084971070818),
 (211, 0.02742042485535409),
 (212, 0.07644707871564382),
 (213, 0.0654653670707977),
 (214, 0.028988551782622416),
 (215, 0.07396705090823068),
 (216, 0.06506000486323554),
 (217, 0.04643634602125721),
 (218, 0.042257712736425826),
 (219, 0.06629935441317959),
 (220, 0.18832944617230335),
 (221, 0.024655683636076894),
 (222, 0.09035079029052512),
 (223, 0.08336550215650926),
 (224, 0.06338656910463875),
 (225, 0.052164053095730106),
 (226, 0.029880715233359837),
 (227, 0.09258200997725513),
 (228, 0.12598815766974242),
 (229, 0.07913425882489307),
 (230, 0.08877935232369503),
 (231, 0.0),
 (232, 0.11952286093343935),
 (233, 0.10811249552346706),
 (234, 0.06776309271789384),
 (235, 0.060717674071891624),
 (236, 0.09759000729485331),
 (237, 0.07049073768502413),
 (238, 0.12777531299998796),
 (239, 0.11097419040461878),
 (240, 0.05096471914376255),
 (241, 0.08964214570007951),
 (242, 0.09416472308615166),
 (243, 0.09968895725584535),
 (244, 0.06277648205743444),
 (245, 0.09107651110783743),
 (246, 0.06601782722034923),
 (247, 0.0),
 (248, 0.04733810683311508),
 (249, 0.14414999403128942),
 (250, 0.0),
 (251, 0.042257712736425826),
 (252, 0.022792115291927588),
 (253, 0.06601782722034923),
 (254, 0.08336550215650926),
 (255, 0.0),
 (256, 0.08199200616907877),
 (257, 0.08696565534786725),
 (258, 0.02344036154692477),
 (259, 0.06388765649999398),
 (260, 0.25110592822973776),
 (261, 0.025482359571881275),
 (262, 0.07476671794188401),
 (263, 0.1057361065275362),
 (264, 0.0),
 (265, 0.029424494316824985),
 (266, 0.11115400287534567),
 (267, 0.07559289460184544),
 (268, 0.02742042485535409),
 (269, 0.033149677206589796),
 (270, 0.1031078524452934),
 (271, 0.0791945516022682),
 (272, 0.030860669992418377),
 (273, 0.024655683636076894),
 (274, 0.08058229640253803),
 (275, 0.12555296411486888),
 (276, 0.06761234037828133),
 (277, 0.06601782722034923),
 (278, 0.1031078524452934),
 (279, 0.1031078524452934),
 (280, 0.0),
 (281, 0.07319250547113999),
 (282, 0.030860669992418377),
 (283, 0.0),
 (284, 0.020203050891044214),
 (285, 0.022792115291927588),
 (286, 0.02258769757263128),
 (287, 0.02742042485535409),
 (288, 0.0),
 (289, 0.05039526306789696),
 (290, 0.06761234037828133),
 (291, 0.0563436169819011),
 (292, 0.10141851056742199),
 (293, 0.03194382824999699),
 (294, 0.11952286093343935),
 (295, 0.10968169942141635),
 (296, 0.040120542714251965),
 (297, 0.04829452884162951),
 (298, 0.0),
 (299, 0.04161251892882394),
 (300, 0.18708286933869708),
 (301, 0.18182745801939793),
 (302, 0.060717674071891624),
 (303, 0.028988551782622416),
 (304, 0.07207499701564471),
 (305, 0.19320245583349133),
 (306, 0.09416472308615166),
 (307, 0.10460520656316097),
 (308, 0.07049073768502413),
 (309, 0.06629935441317959),
 (310, 0.036037498507822355),
 (311, 0.1564921592871903),
 (312, 0.10968169942141635),
 (313, 0.07968190728895957),
 (314, 0.0),
 (315, 0.09107651110783743),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.07207499701564471),
 (320, 0.033806170189140665),
 (321, 0.0),
 (322, 0.22230800575069137),
 (323, 0.033149677206589796),
 (324, 0.026398183867422733),
 (325, 0.11065666703449761),
 (326, 0.05884898863364997),
 (327, 0.028988551782622416),
 (328, 0.0),
 (329, 0.08336550215650926),
 (330, 0.1126872339638022),
 (331, 0.04984447862792268),
 (332, 0.14285714285714285),
 (333, 0.030860669992418377),
 (334, 0.10690449676496976),
 (335, 0.0563436169819011),
 (336, 0.07377111135633174),
 (337, 0.024147264420814756),
 (338, 0.0),
 (339, 0.057142857142857134),
 (340, 0.052164053095730106),
 (341, 0.061721339984836754),
 (342, 0.13662601021279464),
 (343, 0.022792115291927588),
 (344, 0.03138824102871722),
 (345, 0.02366905341655754),
 (346, 0.0),
 (347, 0.0),
 (348, 0.06761234037828133),
 (349, 0.09258200997725513),
 (350, 0.05484084971070818),
 (351, 0.0),
 (352, 0.029424494316824985),
 (353, 0.023904572186687872),
 (354, 0.0),
 (355, 0.040120542714251965),
 (356, 0.09258200997725513),
 (357, 0.0),
 (358, 0.06629935441317959),
 (359, 0.03450327796711771),
 (360, 0.0),
 (361, 0.0563436169819011),
 (362, 0.09759000729485331),
 (363, 0.09116846116771035),
 (364, 0.026082026547865053),
 (365, 0.081199794294115),
 (366, 0.059761430466719674),
 (367, 0.0),
 (368, 0.13522468075656266),
 (369, 0.09258200997725513),
 (370, 0.0563436169819011),
 (371, 0.1031078524452934),
 (372, 0.05345224838248488),
 (373, 0.18018749253911176),
 (374, 0.04438967616184752),
 (375, 0.0432843655349805),
 (376, 0.048795003647426664),
 (377, 0.0),
 (378, 0.0),
 (379, 0.05345224838248487),
 (380, 0.02817180849095055),
 (381, 0.09035079029052512),
 (382, 0.0),
 (383, 0.0515539262226467),
 (384, 0.03253000243161777),
 (385, 0.0),
 (386, 0.024147264420814756),
 (387, 0.02742042485535409),
 (388, 0.0),
 (389, 0.10141851056742199),
 (390, 0.02817180849095055),
 (391, 0.06149400462680908),
 (392, 0.03138824102871722),
 (393, 0.0),
 (394, 0.026082026547865053),
 (395, 0.057142857142857134),
 (396, 0.02366905341655754),
 (397, 0.055577001437672836),
 (398, 0.0),
 (399, 0.02577696311132335),
 (400, 0.10350983390135313),
 (401, 0.03194382824999699),
 (402, 0.061721339984836754),
 (403, 0.11002971203391539),
 (404, 0.06761234037828133),
 (405, 0.030860669992418377),
 (406, 0.021821789023599235),
 (407, 0.026082026547865053),
 (408, 0.035245368842512066),
 (409, 0.0),
 (410, 0.10079052613579392),
 (411, 0.05884898863364997),
 (412, 0.1019294382875251),
 (413, 0.1389425035941821),
 (414, 0.033149677206589796),
 (415, 0.07126966450997983),
 (416, 0.0563436169819011),
 (417, 0.033806170189140665),
 (418, 0.03779644730092272),
 (419, 0.07644707871564382),
 (420, 0.12888481555661674),
 (421, 0.0),
 (422, 0.14754222271266348),
 (423, 0.052164053095730106),
 (424, 0.04040610178208843),
 (425, 0.07100716024967263),
 (426, 0.06195121541733006),
 (427, 0.029424494316824985),
 (428, 0.059350694118669806),
 (429, 0.0),
 (430, 0.052796367734845466),
 (431, 0.02577696311132335),
 (432, 0.12598815766974242),
 (433, 0.033149677206589796),
 (434, 0.0),
 (435, 0.03984095364447979),
 (436, 0.0),
 (437, 0.028988551782622416),
 (438, 0.028571428571428567),
 (439, 0.030860669992418377),
 (440, 0.028571428571428567),
 (441, 0.030358837035945812),
 (442, 0.048795003647426664),
 (443, 0.05884898863364997),
 (444, 0.0),
 (445, 0.028571428571428567),
 (446, 0.02577696311132335),
 (447, 0.023904572186687872),
 (448, 0.026082026547865053),
 (449, 0.05797710356524483),
 (450, 0.026398183867422733),
 (451, 0.026398183867422733),
 (452, 0.03194382824999699),
 (453, 0.02672612419124244),
 (454, 0.12327841818038447),
 (455, 0.024655683636076894),
 (456, 0.0703210846407743),
 (457, 0.08696565534786725),
 (458, 0.04733810683311508),
 (459, 0.036037498507822355),
 (460, 0.028571428571428567),
 (461, 0.1938916835823703),
 (462, 0.0),
 (463, 0.035245368842512066),
 (464, 0.0),
 (465, 0.0),
 (466, 0.2114722130550724),
 (467, 0.09116846116771035),
 (468, 0.030358837035945812),
 (469, 0.0703210846407743),
 (470, 0.04931136727215379),
 (471, 0.08336550215650926),
 (472, 0.08451542547285165),
 (473, 0.1019294382875251),
 (474, 0.0),
 (475, 0.06837634587578276),
 (476, 0.10811249552346706),
 (477, 0.0),
 (478, 0.03984095364447979),
 (479, 0.09508728264112047),
 (480, 0.052164053095730106),
 (481, 0.0),
 (482, 0.030358837035945812),
 (483, 0.1301200097264711),
 (484, 0.03450327796711771),
 (485, 0.0563436169819011),
 (486, 0.05855400437691198),
 (487, 0.14098147537004826),
 (488, 0.07606982611289638),
 (489, 0.0),
 (490, 0.15118578920369088),
 (491, 0.09116846116771035),
 (492, 0.06277648205743444),
 (493, 0.01951800145897066),
 (494, 0.0),
 (495, 0.2162249910469341),
 (496, 0.0),
 (497, 0.0),
 (498, 0.07207499701564471),
 (499, 0.0),
 (500, 0.028571428571428567),
 (501, 0.0880237696271323),
 (502, 0.1546617786679401),
 (503, 0.08336550215650926),
 (504, 0.0),
 (505, 0.14754222271266348),
 (506, 0.03688555567816587),
 (507, 0.24846467329894412),
 (508, 0.11595420713048966),
 (509, 0.02577696311132335),
 (510, 0.10559273546969093),
 (511, 0.09583148474999097),
 (512, 0.060717674071891624),
 (513, 0.11769797726729994),
 (514, 0.059761430466719674),
 (515, 0.027066598098038335),
 (516, 0.02577696311132335),
 (517, 0.0),
 (518, 0.055577001437672836),
 (519, 0.0),
 (520, 0.0),
 (521, 0.028988551782622416),
 (522, 0.0),
 (523, 0.052164053095730106),
 (524, 0.0),
 (525, 0.02492223931396134),
 (526, 0.0),
 (527, 0.0),
 (528, 0.024147264420814756),
 (529, 0.13041013273932528),
 (530, 0.10141851056742199),
 (531, 0.05039526306789696),
 (532, 0.023002185311411804),
 (533, 0.07049073768502413),
 (534, 0.08451542547285165),
 (535, 0.10968169942141635),
 (536, 0.07733088933397005),
 (537, 0.07049073768502413),
 (538, 0.0),
 (539, 0.26089696604360174),
 (540, 0.0563436169819011),
 (541, 0.06900655593423541),
 (542, 0.04040610178208843),
 (543, 0.07824607964359516),
 (544, 0.060717674071891624),
 (545, 0.028571428571428567),
 (546, 0.07207499701564471),
 (547, 0.08964214570007951),
 (548, 0.0),
 (549, 0.1246111965698067),
 (550, 0.028571428571428567),
 (551, 0.0447773662839645),
 (552, 0.0),
 (553, 0.03194382824999699),
 (554, 0.0),
 (555, 0.0497245158098847),
 (556, 0.028988551782622416),
 (557, 0.1449427589131121),
 (558, 0.0),
 (559, 0.03253000243161777),
 (560, 0.04643634602125721),
 (561, 0.03688555567816587),
 (562, 0.0),
 (563, 0.02742042485535409),
 (564, 0.10141851056742199),
 (565, 0.04600437062282361),
 (566, 0.02492223931396134),
 (567, 0.030358837035945812),
 (568, 0.1449427589131121),
 (569, 0.024147264420814756),
 (570, 0.07559289460184544),
 (571, 0.021821789023599235),
 (572, 0.08518354199999197),
 (573, 0.02258769757263128),
 (574, 0.024397501823713332),
 (575, 0.057142857142857134),
 (576, 0.028988551782622416),
 (577, 0.15430334996209188),
 (578, 0.04829452884162951),
 (579, 0.12344267996967351),
 (580, 0.02519763153394848),
 (581, 0.16265001215808886),
 (582, 0.24147264420814754),
 (583, 0.052164053095730106),
 (584, 0.05096471914376255),
 (585, 0.0),
 (586, 0.045584230583855176),
 (587, 0.08017837257372731),
 (588, 0.028988551782622416),
 (589, 0.09862273454430757),
 (590, 0.035245368842512066),
 (591, 0.07824607964359516),
 (592, 0.027066598098038335),
 (593, 0.0),
 (594, 0.055577001437672836),
 (595, 0.13533299049019168),
 (596, 0.09658905768325902),
 (597, 0.05797710356524483),
 (598, 0.03984095364447979),
 (599, 0.03363839659676322),
 (600, 0.07244179326244427),
 (601, 0.03688555567816587),
 (602, 0.04517539514526256),
 (603, 0.057142857142857134),
 (604, 0.06761234037828133),
 (605, 0.0),
 (606, 0.0),
 (607, 0.06716604942594674),
 (608, 0.0),
 (609, 0.047809144373375745),
 (610, 0.06060915267313264),
 (611, 0.02492223931396134),
 (612, 0.07100716024967263),
 (613, 0.03779644730092272),
 (614, 0.060717674071891624),
 (615, 0.033149677206589796),
 (616, 0.0),
 (617, 0.055577001437672836),
 (618, 0.09862273454430757),
 (619, 0.0),
 (620, 0.0),
 (621, 0.07049073768502413),
 (622, 0.02219483808092376),
 (623, 0.0),
 (624, 0.11952286093343936),
 (625, 0.03194382824999699),
 (626, 0.08696565534786725),
 (627, 0.11633501014942217),
 (628, 0.0),
 (629, 0.04984447862792268),
 (630, 0.025482359571881275),
 (631, 0.02742042485535409),
 (632, 0.08336550215650926),
 (633, 0.023904572186687872),
 (634, 0.0857142857142857),
 (635, 0.07476671794188401),
 (636, 0.028571428571428567),
 (637, 0.052796367734845466),
 (638, 0.03450327796711771),
 (639, 0.0),
 (640, 0.0515539262226467),
 (641, 0.0),
 (642, 0.0),
 (643, 0.10690449676496976),
 (644, 0.05797710356524483),
 (645, 0.04829452884162951),
 (646, 0.057142857142857134),
 (647, 0.052164053095730106),
 (648, 0.03253000243161777),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.024397501823713332),
 (653, 0.12298800925361816),
 (654, 0.089554732567929),
 (655, 0.026082026547865053),
 (656, 0.0),
 (657, 0.037332669647327864),
 (658, 0.05413319619607667),
 (659, 0.027066598098038335),
 (660, 0.10350983390135313),
 (661, 0.1690308509457033),
 (662, 0.0),
 (663, 0.0),
 (664, 0.06506000486323554),
 (665, 0.07476671794188401),
 (666, 0.052164053095730106),
 (667, 0.0),
 (668, 0.07049073768502413),
 (669, 0.036037498507822355),
 (670, 0.017817416127494958),
 (671, 0.05413319619607667),
 (672, 0.05797710356524483),
 (673, 0.023218173010628604),
 (674, 0.07733088933397005),
 (675, 0.0515539262226467),
 (676, 0.033149677206589796),
 (677, 0.02742042485535409),
 (678, 0.06277648205743444),
 (679, 0.0),
 (680, 0.08451542547285165),
 (681, 0.035245368842512066),
 (682, 0.024147264420814756),
 (683, 0.0515539262226467),
 (684, 0.0),
 (685, 0.03779644730092272),
 (686, 0.0),
 (687, 0.11952286093343935),
 (688, 0.05039526306789696),
 (689, 0.0),
 (690, 0.029424494316824985),
 (691, 0.10141851056742199),
 (692, 0.12073632210407378),
 (693, 0.0),
 (694, 0.02366905341655754),
 (695, 0.06900655593423542),
 (696, 0.0),
 (697, 0.0),
 (698, 0.02366905341655754),
 (699, 0.0),
 (700, 0.030860669992418377),
 (701, 0.06506000486323554),
 (702, 0.024397501823713332),
 (703, 0.02080625946441197),
 (704, 0.07396705090823068),
 (705, 0.025482359571881275),
 (706, 0.026082026547865053),
 (707, 0.0),
 (708, 0.025482359571881275),
 (709, 0.0),
 (710, 0.0447773662839645),
 (711, 0.06629935441317959),
 (712, 0.0),
 (713, 0.027788500718836418),
 (714, 0.0),
 (715, 0.1057361065275362),
 (716, 0.035245368842512066),
 (717, 0.0),
 (718, 0.04643634602125721),
 (719, 0.0),
 (720, 0.02742042485535409),
 (721, 0.033149677206589796),
 (722, 0.0),
 (723, 0.026398183867422733),
 (724, 0.026082026547865053),
 (725, 0.0),
 (726, 0.0),
 (727, 0.036454130828824455),
 (728, 0.07559289460184544),
 (729, 0.0),
 (730, 0.019262853213235485),
 (731, 0.05484084971070818),
 (732, 0.0791945516022682),
 (733, 0.0447773662839645),
 (734, 0.05039526306789696),
 (735, 0.04984447862792268),
 (736, 0.033149677206589796),
 (737, 0.08017837257372731),
 (738, 0.0),
 (739, 0.03877833671647406),
 (740, 0.13199091933711365),
 (741, 0.05884898863364997),
 (742, 0.03450327796711771),
 (743, 0.02577696311132335),
 (744, 0.06761234037828133),
 (745, 0.06277648205743444),
 (746, 0.08696565534786725),
 (747, 0.02366905341655754),
 (748, 0.03779644730092272),
 (749, 0.0),
 (750, 0.05096471914376255),
 (751, 0.03779644730092272),

Here, we used lamda function to clearify that, sorting by the not index, but by the 2nd number like "0.26089696604360174"

In [521]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])

[(0, 1.0),
 (539, 0.26089696604360174),
 (1192, 0.2581988897471611),
 (260, 0.25110592822973776),
 (1214, 0.24944382578492943),
 (507, 0.24846467329894412),
 (1440, 0.24397501823713333),
 (1916, 0.243599382882345),
 (582, 0.24147264420814754),
 (3728, 0.23904572186687872),
 (74, 0.22677868380553634),
 (3606, 0.2238868314198225),
 (322, 0.22230800575069137),
 (83, 0.22190115272469205),
 (4190, 0.22131333406899523),
 (2329, 0.2173253797873328),
 (1202, 0.21653278478430665),
 (47, 0.2164218276749025),
 (61, 0.2162249910469341),
 (495, 0.2162249910469341),
 (2405, 0.2138089935299395),
 (1533, 0.2125118592516207),
 (942, 0.21251185925162067),
 (972, 0.21251185925162067),
 (466, 0.2114722130550724),
 (1327, 0.21147221305507238),
 (2200, 0.2059714602177749),
 (151, 0.20498001542269692),
 (1199, 0.20283702113484398),
 (973, 0.2),
 (4046, 0.1980534816610477),
 (3160, 0.19518001458970666),
 (4405, 0.19518001458970666),
 (1273, 0.19518001458970663),
 (2782, 0.19518001458970663),
 (2969, 0.19477964490741226),
 (3536, 0.19451950503185494),
 (461, 0.1938916835823703),
 (3325, 0.1938916835823703),
 (305, 0.19320245583349133),
 (36, 0.19194297398747862),
 (931, 0.1916629694999819),
 (150, 0.18869127060994534),
 (220, 0.18832944617230335),
 (27, 0.18752289237539818),
 (2997, 0.18752289237539815),
 (300, 0.18708286933869708),
 (1319, 0.18442777839082936),
 (184, 0.1825741858350554),
 (4, 0.18257418583505536),
 (1069, 0.18257418583505536),
 (301, 0.18182745801939793),
 (373, 0.18018749253911176),
 (67, 0.17928429140015903),
 (46, 0.1765469659009499),
 (7, 0.1763834207376394),
 (2727, 0.17622684421256032),
 (1827, 0.17445567519772937),
 (1342, 0.1739313106957345),
 (149, 0.173137462139922),
 (2492, 0.17251638983558856),
 (26, 0.17142857142857143),
 (208, 0.1690308509457033),
 (661, 0.1690308509457033),
 (4008, 0.1690308509457033),
 (108, 0.16903085094570328),
 (838, 0.16903085094570328),
 (1804, 0.16673100431301852),
 (94, 0.16574838603294897),
 (2511, 0.16574838603294897),
 (1392, 0.16408253082847338),
 (581, 0.16265001215808886),
 (1295, 0.16239958858823),
 (4336, 0.16239958858823),
 (168, 0.16035674514745463),
 (1379, 0.16035674514745463),
 (31, 0.15971914124998493),
 (91, 0.15971914124998493),
 (3626, 0.15694120514358612),
 (311, 0.1564921592871903),
 (1961, 0.1553638665664663),
 (502, 0.1546617786679401),
 (111, 0.15430334996209188),
 (577, 0.15430334996209188),
 (3352, 0.15430334996209188),
 (158, 0.15289415743128765),
 (1353, 0.15289415743128765),
 (1176, 0.15179418517972906),
 (2165, 0.15179418517972906),
 (172, 0.15118578920369088),
 (490, 0.15118578920369088),
 (17, 0.15026857675938213),
 (1934, 0.14953343588376802),
 (422, 0.14754222271266348),
 (505, 0.14754222271266348),
 (1484, 0.14754222271266348),
 (41, 0.14638501094227999),
 (84, 0.1456438162508838),
 (52, 0.1449427589131121),
 (557, 0.1449427589131121),
 (568, 0.1449427589131121),
 (2682, 0.1449427589131121),
 (56, 0.14414999403128942),
 (249, 0.14414999403128942),
 (2580, 0.14414999403128942),
 (3997, 0.14414999403128942),
 (332, 0.14285714285714285),
 (1218, 0.14285714285714285),
 (1320, 0.14201432049934523),
 (487, 0.14098147537004826),
 (1325, 0.14098147537004826),
 (187, 0.14085904245475275),
 (1941, 0.14085904245475275),
 (1669, 0.1406421692815486),
 (2129, 0.1406421692815486),
 (2476, 0.1406421692815486),
 (4348, 0.1406421692815486),
 (413, 0.1389425035941821),
 (1829, 0.13801311186847084),
 (2616, 0.13801311186847084),
 (2968, 0.13801311186847084),
 (4490, 0.13801311186847084),
 (2869, 0.13801311186847082),
 (1013, 0.13710212427677043),
 (3407, 0.13710212427677043),
 (3620, 0.13710212427677043),
 (342, 0.13662601021279464),
 (127, 0.13572417850765922),
 (595, 0.13533299049019168),
 (1297, 0.13533299049019168),
 (134, 0.13522468075656266),
 (368, 0.13522468075656266),
 (1156, 0.13522468075656266),
 (3671, 0.1336306209562122),
 (1000, 0.13316902848554255),
 (68, 0.13259870882635919),
 (1045, 0.13259870882635919),
 (1094, 0.13259870882635919),
 (1654, 0.13259870882635919),
 (2374, 0.13259870882635919),
 (3374, 0.13259870882635919),
 (740, 0.13199091933711365),
 (1711, 0.1309307341415954),
 (529, 0.13041013273932528),
 (778, 0.13041013273932528),
 (1613, 0.13041013273932528),
 (483, 0.1301200097264711),
 (1743, 0.1301200097264711),
 (420, 0.12888481555661674),
 (1035, 0.12888481555661674),
 (1737, 0.12880163722232754),
 (238, 0.12777531299998796),
 (939, 0.12777531299998796),
 (2709, 0.12741179785940637),
 (3307, 0.12741179785940637),
 (1571, 0.1267731382092775),
 (4201, 0.1267731382092775),
 (228, 0.12598815766974242),
 (432, 0.12598815766974242),
 (3405, 0.12598815766974242),
 (28, 0.12555296411486888),
 (275, 0.12555296411486888),
 (1272, 0.12555296411486888),
 (2071, 0.12555296411486888),
 (2864, 0.12555296411486888),
 (4673, 0.12555296411486888),
 (549, 0.1246111965698067),
 (95, 0.12461119656980668),
 (50, 0.12344267996967351),
 (72, 0.12344267996967351),
 (579, 0.12344267996967351),
 (1978, 0.12344267996967351),
 (454, 0.12327841818038447),
 (2543, 0.12327841818038447),
 (1508, 0.12327841818038446),
 (653, 0.12298800925361816),
 (808, 0.12298800925361816),
 (123, 0.12198750911856666),
 (692, 0.12073632210407378),
 (1275, 0.12073632210407378),
 (1475, 0.12073632210407378),
 (3145, 0.12036162814275589),
 (169, 0.11952286093343936),
 (624, 0.11952286093343936),
 (2255, 0.11952286093343936),
 (3628, 0.11952286093343936),
 (3719, 0.11952286093343936),
 (166, 0.11952286093343935),
 (232, 0.11952286093343935),
 (294, 0.11952286093343935),
 (687, 0.11952286093343935),
 (859, 0.11952286093343935),
 (1612, 0.11952286093343935),
 (1570, 0.1187013882373396),
 (5, 0.1183452670827877),
 (10, 0.11769797726729994),
 (513, 0.11769797726729994),
 (1029, 0.11769797726729994),
 (2579, 0.11769797726729994),
 (3006, 0.11769797726729994),
 (199, 0.11720180773462385),
 (81, 0.11710800875382396),
 (627, 0.11633501014942217),
 (1369, 0.11633501014942217),
 (1723, 0.11633501014942217),
 (2319, 0.11633501014942217),
 (3998, 0.11633501014942217),
 (4016, 0.11633501014942217),
 (87, 0.11595420713048966),
 (126, 0.11595420713048966),
 (508, 0.11595420713048966),
 (777, 0.11501092655705902),
 (14, 0.11428571428571427),
 (854, 0.11428571428571427),
 (900, 0.11428571428571427),
 (1193, 0.11428571428571427),
 (2009, 0.11428571428571427),
 (2446, 0.11428571428571427),
 (3496, 0.11428571428571427),
 (1520, 0.11338934190276817),
 (1717, 0.11338934190276817),
 (2630, 0.11338934190276817),
 (3659, 0.11338934190276817),
 (4133, 0.11338934190276817),
 (141, 0.11338934190276816),
 (1017, 0.1129384878631564),
 (1493, 0.1129384878631564),
 (2435, 0.1129384878631564),
 (131, 0.1126872339638022),
 (330, 0.1126872339638022),
 (1080, 0.1126872339638022),
 (1292, 0.1126872339638022),
 (3338, 0.1126872339638022),
 (3618, 0.1126872339638022),
 (4095, 0.1126872339638022),
 (18, 0.11194341570991125),
 (102, 0.11194341570991125),
 (2102, 0.11194341570991125),
 (2756, 0.11194341570991125),
 (174, 0.11115400287534567),
 (266, 0.11115400287534567),
 (2068, 0.11115400287534567),
 (2177, 0.11115400287534567),
 (239, 0.11097419040461878),
 (3779, 0.11065666703449763),
 (35, 0.11065666703449761),
 (325, 0.11065666703449761),
 (773, 0.11065666703449761),
 (1154, 0.11065666703449761),
 (2517, 0.11065666703449761),
 (3053, 0.11065666703449761),
 (3952, 0.11065666703449761),
 (403, 0.11002971203391539),
 (295, 0.10968169942141635),
 (312, 0.10968169942141635),
 (535, 0.10968169942141635),
 (986, 0.10968169942141635),
 (1271, 0.10968169942141635),
 (3100, 0.10968169942141635),
 (4077, 0.10968169942141635),
 (754, 0.10826639239215334),
 (4228, 0.10826639239215334),
 (139, 0.10821091383745127),
 (4545, 0.10821091383745125),
 (105, 0.10811249552346706),
 (233, 0.10811249552346706),
 (476, 0.10811249552346706),
 (2452, 0.10811249552346706),
 (2758, 0.10811249552346706),
 (3837, 0.10811249552346706),
 (4196, 0.10811249552346706),
 (4623, 0.10811249552346706),
 (182, 0.10690449676496976),
 (334, 0.10690449676496976),
 (643, 0.10690449676496976),
 (898, 0.10690449676496976),
 (1054, 0.10690449676496976),
 (1107, 0.10690449676496976),
 (3781, 0.10690449676496976),
 (85, 0.10631548679075009),
 (33, 0.1057361065275362),
 (148, 0.1057361065275362),
 (157, 0.1057361065275362),
 (263, 0.1057361065275362),
 (715, 0.1057361065275362),
 (935, 0.1057361065275362),
 (1278, 0.1057361065275362),
 (1299, 0.1057361065275362),
 (1497, 0.1057361065275362),
 (2558, 0.1057361065275362),
 (2656, 0.1057361065275362),
 (4331, 0.1057361065275362),
 (129, 0.10559273546969093),
 (510, 0.10559273546969093),
 (1084, 0.10559273546969093),
 (3441, 0.10559273546969093),
 (3462, 0.10559273546969093),
 (4043, 0.10559273546969093),
 (307, 0.10460520656316097),
 (1231, 0.10432810619146021),
 (400, 0.10350983390135313),
 (660, 0.10350983390135313),
 (781, 0.10350983390135313),
 (1938, 0.10350983390135313),
 (2657, 0.10350983390135313),
 (4254, 0.10350983390135313),
 (270, 0.1031078524452934),
 (278, 0.1031078524452934),
 (279, 0.1031078524452934),
 (371, 0.1031078524452934),
 (870, 0.1031078524452934),
 (1200, 0.1031078524452934),
 (1435, 0.1031078524452934),
 (412, 0.1019294382875251),
 (473, 0.1019294382875251),
 (813, 0.1019294382875251),
 (933, 0.1019294382875251),
 (1274, 0.1019294382875251),
 (1999, 0.1019294382875251),
 (2280, 0.1019294382875251),
 (292, 0.10141851056742199),
 (389, 0.10141851056742199),
 (530, 0.10141851056742199),
 (564, 0.10141851056742199),
 (691, 0.10141851056742199),
 (920, 0.10141851056742199),
 (1075, 0.10141851056742199),
 (1404, 0.10141851056742199),
 (2647, 0.10141851056742199),
 (3091, 0.10141851056742199),
 (3734, 0.10141851056742199),
 (410, 0.10079052613579392),
 (1819, 0.10079052613579392),
 (243, 0.09968895725584535),
 (785, 0.09960238411119947),
 (1087, 0.09960238411119947),
 (791, 0.0994490316197694),
 (1470, 0.0994490316197694),
 (1585, 0.0994490316197694),
 (1682, 0.0994490316197694),
 (1752, 0.0994490316197694),
 (2392, 0.0994490316197694),
 (2648, 0.0994490316197694),
 (589, 0.09862273454430757),
 (618, 0.09862273454430757),
 (1355, 0.09862273454430757),
 (2592, 0.09862273454430757),
 (43, 0.09759000729485333),
 (1842, 0.09759000729485333),
 (2484, 0.09759000729485333),
 (2792, 0.09759000729485333),
 (3152, 0.09759000729485333),
 (23, 0.09759000729485331),
 (142, 0.09759000729485331),
 (236, 0.09759000729485331),
 (362, 0.09759000729485331),
 (2089, 0.09759000729485331),
 (160, 0.09694584179118515),
 (206, 0.09694584179118515),
 (596, 0.09658905768325902),
 (1414, 0.09658905768325902),
 (12, 0.09583148474999097),
 (122, 0.09583148474999097),
 (511, 0.09583148474999097),
 (794, 0.09583148474999097),
 (922, 0.09583148474999097),
 (1025, 0.09583148474999097),
 (1304, 0.09583148474999097),
 (2836, 0.09583148474999097),
 (1828, 0.09561828874675149),
 (1920, 0.09561828874675149),
 (479, 0.09508728264112047),
 (1276, 0.09467621366623016),
 (21, 0.09416472308615166),
 (164, 0.09416472308615166),
 (242, 0.09416472308615166),
 (306, 0.09416472308615166),
 (960, 0.09416472308615166),
 (1247, 0.09416472308615166),
 (1519, 0.09416472308615166),
 (2813, 0.09416472308615166),
 (4468, 0.09416472308615166),
 (799, 0.09390602830316849),
 (1492, 0.09376144618769908),
 (2270, 0.09376144618769908),
 (2384, 0.09376144618769908),
 (2852, 0.09376144618769908),
 (4353, 0.09376144618769908),
 (4502, 0.09376144618769908),
 (4516, 0.09376144618769908),
 (4654, 0.09376144618769908),
 (2444, 0.09333167411831966),
 (75, 0.09258200997725513),
 (227, 0.09258200997725513),
 (349, 0.09258200997725513),
 (356, 0.09258200997725513),
 (369, 0.09258200997725513),
 (775, 0.09258200997725513),
 (901, 0.09258200997725513),
 (978, 0.09258200997725513),
 (1002, 0.09258200997725513),
 (1374, 0.09258200997725513),
 (1696, 0.09258200997725513),
 (1786, 0.09258200997725513),
 (3447, 0.09258200997725513),
 (3535, 0.09258200997725513),
 (3814, 0.09258200997725513),
 (4626, 0.09258200997725513),
 (63, 0.09200874124564722),
 (107, 0.09200874124564722),
 (170, 0.09200874124564722),
 (812, 0.09200874124564722),
 (2001, 0.09200874124564722),
 (2966, 0.09200874124564722),
 (32, 0.09116846116771035),
 (45, 0.09116846116771035),
 (363, 0.09116846116771035),
 (467, 0.09116846116771035),
 (491, 0.09116846116771035),
 (2494, 0.09116846116771035),
 (88, 0.09107651110783743),
 (112, 0.09107651110783743),
 (121, 0.09107651110783743),
 (245, 0.09107651110783743),
 (315, 0.09107651110783743),
 (814, 0.09107651110783743),
 (894, 0.09107651110783743),
 (937, 0.09107651110783743),
 (2163, 0.09107651110783743),
 (3299, 0.09107651110783743),
 (222, 0.09035079029052512),
 (381, 0.09035079029052512),
 (2876, 0.09035079029052512),
 (4737, 0.09035079029052512),
 (2382, 0.09009374626955588),
 (1, 0.08964214570007951),
 (96, 0.08964214570007951),
 (241, 0.08964214570007951),
 (547, 0.08964214570007951),
 (1111, 0.08964214570007951),
 (1140, 0.08964214570007951),
 (1267, 0.08964214570007951),
 (2243, 0.08964214570007951),
 (2247, 0.08964214570007951),
 (2300, 0.08964214570007951),
 (2790, 0.08964214570007951),
 (3089, 0.08964214570007951),
 (4257, 0.08964214570007951),
 (4657, 0.08964214570007951),
 (654, 0.089554732567929),
 (1280, 0.089554732567929),
 (103, 0.08877935232369503),
 (230, 0.08877935232369503),
 (1874, 0.08877935232369503),
 (39, 0.08827348295047496),
 (86, 0.08827348295047496),
 (98, 0.08827348295047496),
 (101, 0.08827348295047496),
 (203, 0.08827348295047496),
 (786, 0.08827348295047496),
 (899, 0.08827348295047496),
 (1205, 0.08827348295047496),
 (1469, 0.08827348295047496),
 (3426, 0.08827348295047495),
 (501, 0.0880237696271323),
 (1824, 0.0880237696271323),
 (19, 0.08728715609439694),
 (193, 0.08728715609439694),
 (1137, 0.08728715609439694),
 (1401, 0.08728715609439694),
 (2095, 0.08728715609439694),
 (2246, 0.08728715609439694),
 (2335, 0.08728715609439694),
 (3067, 0.08728715609439694),
 (3216, 0.08728715609439694),
 (3439, 0.08728715609439694),
 (4163, 0.08728715609439694),
 (4492, 0.08728715609439694),
 (4718, 0.08728715609439694),
 (257, 0.08696565534786725),
 (457, 0.08696565534786725),
 (626, 0.08696565534786725),
 (746, 0.08696565534786725),
 (787, 0.08696565534786725),
 (3026, 0.08696565534786725),
 (3138, 0.08696565534786725),
 (3233, 0.08696565534786725),
 (3308, 0.08696565534786725),
 (3421, 0.08696565534786725),
 (153, 0.086568731069961),
 (1894, 0.086568731069961),
 (1530, 0.08656873106996099),
 (51, 0.08586775814821836),
 (1635, 0.08586775814821836),
 (207, 0.0857142857142857),
 (634, 0.0857142857142857),
 (1159, 0.0857142857142857),
 (2249, 0.0857142857142857),
 (2640, 0.0857142857142857),
 (572, 0.08518354199999197),
 (1922, 0.08518354199999197),
 (3429, 0.08518354199999197),
 (37, 0.08451542547285165),
 (472, 0.08451542547285165),
 (534, 0.08451542547285165),
 (680, 0.08451542547285165),
 (776, 0.08451542547285165),
 (885, 0.08451542547285165),
 (985, 0.08451542547285165),
 (1397, 0.08451542547285165),
 (1610, 0.08451542547285165),
 (1617, 0.08451542547285165),
 (1651, 0.08451542547285165),
 (2161, 0.08451542547285165),
 (2199, 0.08451542547285165),
 (2708, 0.08451542547285165),
 (2797, 0.08451542547285165),
 (3387, 0.08451542547285165),
 (3525, 0.08451542547285165),
 (4059, 0.08451542547285165),
 (4431, 0.08451542547285165),
 (4641, 0.08451542547285165),
 (190, 0.08386278693775347),
 (82, 0.08336550215650926),
 (223, 0.08336550215650926),
 (254, 0.08336550215650926),
 (329, 0.08336550215650926),
 (471, 0.08336550215650926),
 (503, 0.08336550215650926),
 (632, 0.08336550215650926),
 (2679, 0.08336550215650926),
 (3353, 0.08336550215650926),
 (3468, 0.08336550215650926),
 (3908, 0.08336550215650926),
 (16, 0.08226127456606226),
 (71, 0.08226127456606226),
 (138, 0.08226127456606226),
 (1556, 0.08226127456606226),
 (1761, 0.08226127456606226),
 (2816, 0.08226127456606226),
 (4053, 0.08226127456606226),
 (4451, 0.08226127456606226),
 (62, 0.08199200616907877),
 (189, 0.08199200616907877),
 (205, 0.08199200616907877),
 (256, 0.08199200616907877),
 (850, 0.08199200616907877),
 (1043, 0.08199200616907877),
 (1321, 0.08199200616907877),
 (1660, 0.08199200616907877),
 (2322, 0.08199200616907877),
 (2759, 0.08199200616907877),
 (2785, 0.08199200616907877),
 (2880, 0.08199200616907877),
 (3153, 0.08199200616907877),
 (3251, 0.08199200616907877),
 (4473, 0.08199200616907877),
 (4568, 0.08199200616907877),
 (11, 0.081199794294115),
 (70, 0.081199794294115),
 (365, 0.081199794294115),
 (1287, 0.081199794294115),
 (1288, 0.081199794294115),
 (1363, 0.081199794294115),
 (2588, 0.081199794294115),
 (3204, 0.081199794294115),
 (3699, 0.081199794294115),
 (274, 0.08058229640253803),
 (59, 0.08024108542850393),
 (587, 0.08017837257372731),
 (737, 0.08017837257372731),
 (2159, 0.08017837257372731),
 (4640, 0.08017837257372731),
 (125, 0.07985957062499247),
 (109, 0.07968190728895957),
 (313, 0.07968190728895957),
 (800, 0.07968190728895957),
 (1286, 0.07968190728895957),
 (1517, 0.07968190728895957),
 (2157, 0.07968190728895957),
 (2313, 0.07968190728895957),
 (2377, 0.07968190728895957),
 (2406, 0.07968190728895957),
 (2547, 0.07968190728895957),
 (2655, 0.07968190728895957),
 (3396, 0.07968190728895957),
 (3428, 0.07968190728895957),
 (3830, 0.07968190728895957),
 (4412, 0.07968190728895957),
 (271, 0.0791945516022682),
 (732, 0.0791945516022682),
 (908, 0.0791945516022682),
 (2391, 0.0791945516022682),
 (2827, 0.0791945516022682),
 (3020, 0.0791945516022682),
 (3905, 0.0791945516022682),
 (229, 0.07913425882489307),
 (76, 0.07824607964359516),
 (79, 0.07824607964359516),
 (543, 0.07824607964359516),
 (591, 0.07824607964359516),
 (784, 0.07824607964359516),
 (977, 0.07824607964359516),
 (1173, 0.07824607964359516),
 (1323, 0.07824607964359516),
 (2017, 0.07824607964359516),
 (2048, 0.07824607964359516),
 (2359, 0.07824607964359516),
 (2697, 0.07824607964359516),
 (2914, 0.07824607964359516),
 (4081, 0.07824607964359516),
 (4121, 0.07824607964359516),
 (2350, 0.07824607964359515),
 (200, 0.07755667343294811),
 (1003, 0.07755667343294811),
 (1346, 0.07755667343294811),
 (1765, 0.07755667343294811),
 (2132, 0.07755667343294811),
 (2208, 0.07755667343294811),
 (3070, 0.07755667343294811),
 (3980, 0.07755667343294811),
 (4004, 0.07755667343294811),
 (9, 0.07733088933397005),
 (536, 0.07733088933397005),
 (674, 0.07733088933397005),
 (1619, 0.07733088933397005),
 (1628, 0.07733088933397005),
 (2237, 0.07733088933397005),
 (3186, 0.07733088933397005),
 (55, 0.07655590023509526),
 (212, 0.07644707871564382),
 (419, 0.07644707871564382),
 (782, 0.07644707871564382),
 (1442, 0.07644707871564382),
 (1879, 0.07644707871564382),
 (2646, 0.07644707871564382),
 (488, 0.07606982611289638),
 (179, 0.07559289460184544),
 (267, 0.07559289460184544),
 (570, 0.07559289460184544),
 (728, 0.07559289460184544),
 (827, 0.07559289460184544),
 (1144, 0.07559289460184544),
 (1166, 0.07559289460184544),
 (1290, 0.07559289460184544),
 (1766, 0.07559289460184544),
 (2529, 0.07559289460184544),
 (2694, 0.07559289460184544),
 (2783, 0.07559289460184544),
 (3388, 0.07559289460184544),
 (3820, 0.07559289460184544),
 (3992, 0.07559289460184544),
 (4097, 0.07559289460184544),
 (4403, 0.07559289460184544),
 (4443, 0.07559289460184544),
 (2052, 0.07476671794188403),
 (97, 0.07476671794188401),
 (262, 0.07476671794188401),
 (635, 0.07476671794188401),
 (665, 0.07476671794188401),
 (995, 0.07476671794188401),
 (1338, 0.07476671794188401),
 (1697, 0.07476671794188401),
 (1992, 0.07476671794188401),
 (183, 0.07466533929465573),
 (215, 0.07396705090823068),
 (704, 0.07396705090823068),
 (752, 0.07396705090823068),
 (1016, 0.07396705090823068),
 (2014, 0.07396705090823068),
 (2316, 0.07396705090823068),
 (4343, 0.07396705090823068),
 (100, 0.07377111135633174),
 (336, 0.07377111135633174),
 (1164, 0.07377111135633174),
 (1260, 0.07377111135633174),
 (1733, 0.07377111135633174),
 (1770, 0.07377111135633174),
 (1986, 0.07377111135633174),
 (2110, 0.07377111135633174),
 (3239, 0.07377111135633174),
 (3667, 0.07377111135633174),
 (3974, 0.07377111135633174),
 (4290, 0.07377111135633174),
 (30, 0.07319250547113999),

But we only neede 5 item

In [522]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

[(539, 0.26089696604360174),
 (1192, 0.2581988897471611),
 (260, 0.25110592822973776),
 (1214, 0.24944382578492943),
 (507, 0.24846467329894412)]

Suming up it all, we conlude:

In [523]:
from operator import index
def recommned(movie):
  movie_index = new_df[new_df['title'] == movie].index[0]
  distances = similarity[movie_index]
  movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]

  for i in movie_list:
    print(i[0])

In [524]:
recommned('Avatar')

539
1192
260
1214
507

In [525]:
new_df.iloc[1216]

movie_id                                                10641
title                                      Autumn in New York
tags        autumn in new york follow the sexual exploit o...
Name: 1216, dtype: object

In [526]:
new_df.iloc[1216].title

'Autumn in New York'

In [537]:
from operator import index
def recommned(movie):
  movie_index = new_df[new_df['title'] == movie].index[0]
  distances = similarity[movie_index]
  movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]

  for i in movie_list:
    print(new_df.iloc[i[0]].title)
    # print(i[0])

In [538]:
recommned('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman & Robin
Batman